name: Build (debug)
description: Builds debugging android apk
runs:
  using: 'composite'
  steps:
    - name: Set BUILD_DIR
      shell: bash
      run: echo BUILD_DIR="app/build/outputs/apk/debug" >> "$GITHUB_ENV"

    - name: Set APK_FILE location
      shell: bash
      run: echo "APK_FILE_DEBUG=${{ env.BUILD_DIR }}/${{ env.APP_NAME_DEBUG }}.apk" >> "$GITHUB_ENV"

    - uses: actions/checkout@v4
    - name: Build debug apk
      shell: bash
      run: |
        ./gradlew assembleDebug --no-daemon || exit $?
        mv ${{ env.BUILD_DIR }}/*.apk "${{ env.APK_FILE_DEBUG }}"

    # - name: Build debug bundle
    #   run: ./gradlew bundleDebug --no-daemon
